# -*- coding: utf-8 -*-
"""Retirement Calculator - 11.22

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KPLooe09fLvAhhQ9OzP69tH1qv7qMCCn
"""

import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import datetime

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="NerdWallet Wealth Partners | Retire with Confidence",
    layout="wide"
)

# --- BRANDING & CSS ---
st.markdown("""
<style>
    /* NerdWallet-inspired Color Palette */
    :root {
        --primary-green: #00B140;
        --hover-green: #008F4F;
        --text-black: #181818;
        --bg-gray: #F4F4F4;
        --alert-red: #D93025;
        --cone-opacity: 0.2;
    }

    /* Typography */
    h1, h2, h3 {
        color: var(--text-black);
        font-family: "Graphik", sans-serif;
    }

    /* Custom Metric Card */
    .metric-card {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 8px;
        border: 1px solid #e6e6e6;
        border-top: 4px solid var(--primary-green);
        box-shadow: 0 1px 3px rgba(0,0,0,0.05);
        margin-bottom: 10px;
    }

    /* Primary Buttons */
    .stButton>button {
        width: 100%;
        border-radius: 4px; /* Sharper, more professional radius */
        height: 3em;
        background-color: var(--primary-green);
        color: white;
        font-weight: bold;
        border: none;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        transition: background-color 0.2s;
    }
    .stButton>button:hover {
        background-color: var(--hover-green);
        color: white;
    }

    /* Sidebar Styling */
    [data-testid="stSidebar"] {
        background-color: #fafafa;
        border-right: 1px solid #e6e6e6;
    }

    /* Custom Logo Text */
    .brand-text {
        font-size: 24px;
        font-weight: 900;
        color: var(--text-black);
        text-transform: uppercase;
        letter-spacing: -0.5px;
    }
    .brand-accent {
        color: var(--primary-green);
    }
    .sub-brand {
        font-size: 14px;
        color: #666;
        font-weight: 500;
        text-transform: uppercase;
        letter-spacing: 1px;
        margin-top: -5px;
    }

    /* Link Styling */
    a {
        color: var(--primary-green);
        text-decoration: none;
        font-weight: bold;
    }
    a:hover {
        text-decoration: underline;
    }
</style>
""", unsafe_allow_html=True)

# --- 1. DATA STORAGE CONSTANTS ---
DEFAULT_COMPANY_PARAMS = {
    "tax_rate_inc": 0.30,
    "tax_rate_inv": 0.20,
    "inflation": 0.03,
    "pre_ret_return": 0.05,
    "post_ret_return": 0.06,
    "advisor_fee": 0.006
}

DEFAULT_CLIENT_INPUTS = {
    'in_age': 33,
    'in_capital': 400000,
    'in_income': 250000,
    'in_expenses': 100000, # Default 100k
    'in_savings': 20000,
    'in_growth': 5.0,
    'in_retire_age': 65,
    'in_end_age': 90
}

SS_WAGE_BASE = 168600
SS_TAX_RATE = 0.062

# --- 2. SESSION STATE MANAGEMENT ---
if 'page' not in st.session_state:
    st.session_state.page = 'input'

if 'show_optimizer' not in st.session_state:
    st.session_state.show_optimizer = False

if 'show_warning' not in st.session_state:
    st.session_state.show_warning = False

# A. Initialize Client Inputs (The Mutable Edit State)
for key, val in DEFAULT_CLIENT_INPUTS.items():
    if key not in st.session_state:
        st.session_state[key] = val

# B. Initialize Company Params (The Admin State)
if 'company_params' not in st.session_state:
    st.session_state.company_params = DEFAULT_COMPANY_PARAMS.copy()
else:
    # Backward compatibility check
    for key, val in DEFAULT_COMPANY_PARAMS.items():
        if key not in st.session_state.company_params:
            st.session_state.company_params[key] = val

# C. Initialize Locked Scenario (The Immutable Run State)
if 'locked_scenario' not in st.session_state or not st.session_state.locked_scenario:
    st.session_state.locked_scenario = {
        'age': DEFAULT_CLIENT_INPUTS['in_age'],
        'capital': DEFAULT_CLIENT_INPUTS['in_capital'],
        'income': DEFAULT_CLIENT_INPUTS['in_income'],
        'expenses': DEFAULT_CLIENT_INPUTS['in_expenses'],
        'savings': DEFAULT_CLIENT_INPUTS['in_savings'],
        'growth': DEFAULT_CLIENT_INPUTS['in_growth'],
        'retire_age': DEFAULT_CLIENT_INPUTS['in_retire_age'],
        'end_age': DEFAULT_CLIENT_INPUTS['in_end_age']
    }

# --- 3. HELPER FUNCTIONS & TRANSITIONS ---

def save_inputs_to_locked():
    """
    Snapshots the current widget values into locked_scenario.
    """
    st.session_state.locked_scenario = {
        'age': st.session_state.in_age,
        'capital': st.session_state.in_capital,
        'income': st.session_state.in_income,
        'expenses': st.session_state.in_expenses,
        'savings': st.session_state.in_savings,
        'growth': st.session_state.in_growth,
        'retire_age': st.session_state.in_retire_age,
        'end_age': st.session_state.in_end_age
    }

def check_inputs():
    save_inputs_to_locked()

    inc = st.session_state.in_income
    exp = st.session_state.in_expenses
    sav = st.session_state.in_savings

    params = st.session_state.company_params
    tax_rate = params['tax_rate_inc']

    fica = min(inc, SS_WAGE_BASE) * SS_TAX_RATE
    tax_bill = inc * tax_rate
    surplus = inc - tax_bill - fica - exp

    if sav > surplus:
        st.session_state.show_warning = True
    else:
        st.session_state.page = 'output'
        st.session_state.show_optimizer = False

def proceed_despite_warning():
    st.session_state.show_warning = False
    st.session_state.page = 'output'
    st.session_state.show_optimizer = False

def go_back_to_edit():
    st.session_state.show_warning = False
    ls = st.session_state.locked_scenario
    st.session_state.in_age = ls['age']
    st.session_state.in_capital = ls['capital']
    st.session_state.in_income = ls['income']
    st.session_state.in_expenses = ls['expenses']
    st.session_state.in_savings = ls['savings']
    st.session_state.in_growth = ls['growth']
    st.session_state.in_retire_age = ls['retire_age']
    st.session_state.in_end_age = ls['end_age']

def go_to_input():
    st.session_state.page = 'input'

def enable_optimizer():
    st.session_state.show_optimizer = True

def restore_admin_defaults():
    st.session_state.company_params = DEFAULT_COMPANY_PARAMS.copy()
    if 'ss_override' in st.session_state:
        del st.session_state.ss_override
    st.rerun()

def restore_client_defaults():
    for key, val in DEFAULT_CLIENT_INPUTS.items():
        st.session_state[key] = val
    st.rerun()

def calculate_primary_insurance_amount(annual_income):
    applicable_income = min(annual_income, SS_WAGE_BASE)
    monthly_income = applicable_income / 12
    bp1 = 1174
    bp2 = 7078
    pia = 0
    pia += 0.90 * min(monthly_income, bp1)
    if monthly_income > bp1:
        pia += 0.32 * min(monthly_income - bp1, bp2 - bp1)
    if monthly_income > bp2:
        pia += 0.15 * (monthly_income - bp2)
    return round(pia)

# --- 4. CORE CALCULATION ENGINE ---

def run_monte_carlo(starting_capital, annual_savings, annual_spend, current_age, retire_age, savings_growth_rate, years_to_sim, ss_monthly_benefit, params, return_paths=False):
    rng = np.random.default_rng(seed=42)
    years_to_sim = int(years_to_sim)

    tax_rate_inv = params['tax_rate_inv']
    inflation = params['inflation']
    pre_ret_return = params['pre_ret_return']
    post_ret_return = params['post_ret_return']
    advisor_fee = params['advisor_fee']

    net_pre = pre_ret_return - advisor_fee - (pre_ret_return * tax_rate_inv)
    net_post = post_ret_return - advisor_fee - (post_ret_return * tax_rate_inv)

    simulations = 400
    success_count = 0
    ruin_ages = []

    # If we need paths, we store them here. Rows = simulations, Cols = years
    all_paths = []

    for i in range(simulations):
        age = current_age
        wealth = starting_capital
        savings = annual_savings
        spend = annual_spend
        current_ss_annual = ss_monthly_benefit * 12

        path = []

        volatility = rng.normal(0, 0.12, years_to_sim)
        is_ruined = False

        for year in range(years_to_sim):
            if age < retire_age:
                growth = net_pre + (volatility[year] * 0.5)
                wealth = wealth * (1 + growth) + savings
                savings *= (1 + (savings_growth_rate / 100))
                spend *= (1 + inflation)
                current_ss_annual *= (1 + inflation)
            else:
                portfolio_withdrawal = spend - current_ss_annual
                if portfolio_withdrawal < 0: portfolio_withdrawal = 0

                # Gross up for tax
                gross_withdrawal = portfolio_withdrawal / (1 - tax_rate_inv)

                growth = net_post + volatility[year]
                wealth = wealth * (1 + growth) - gross_withdrawal

                spend *= (1 + inflation)
                current_ss_annual *= (1 + inflation)

            # Check Ruin
            if wealth <= 0:
                is_ruined = True
                wealth = 0 # Floor at 0
                # Note: We continue the loop to fill the path with 0s for array consistency
                if not path or path[-1] > 0: # Capture age only once
                    ruin_ages.append(age)

            path.append(wealth)
            age += 1

        if not is_ruined:
            success_count += 1
            ruin_ages.append(current_age + years_to_sim)

        if return_paths:
            all_paths.append(path)

    probability = (success_count / simulations) * 100
    median_ruin = np.median(ruin_ages) if ruin_ages else (current_age + years_to_sim)

    path_data = {}
    if return_paths and all_paths:
        # Convert to numpy array for percentile calc [sims, years]
        arr_paths = np.array(all_paths)

        # Calculate logical ranges:
        # Worst 25% roughly approximated by 5th to 25th percentile
        # Middle 50% is 25th to 75th percentile (The likely outcome)
        # Best 25% roughly approximated by 75th to 95th percentile

        path_data['p05'] = np.percentile(arr_paths, 5, axis=0)
        path_data['p25'] = np.percentile(arr_paths, 25, axis=0)
        path_data['p50'] = np.percentile(arr_paths, 50, axis=0) # Median
        path_data['p75'] = np.percentile(arr_paths, 75, axis=0)
        path_data['p95'] = np.percentile(arr_paths, 95, axis=0)

        path_data['final_values'] = arr_paths[:, -1]

    return probability, median_ruin, path_data

def generate_detailed_ledger(starting_capital, annual_income, annual_savings, annual_spend, current_age, retire_age, savings_growth_rate, years_to_sim, ss_monthly_benefit, params):
    years_to_sim = int(years_to_sim)
    tax_rate_inc = params['tax_rate_inc']
    tax_rate_inv = params['tax_rate_inv']
    advisor_fee = params['advisor_fee']
    inflation = params['inflation']
    pre_ret_return = params['pre_ret_return']
    post_ret_return = params['post_ret_return']

    net_pre = pre_ret_return - advisor_fee - (pre_ret_return * tax_rate_inv)
    net_post = post_ret_return - advisor_fee - (post_ret_return * tax_rate_inv)

    data = []
    age = current_age
    wealth = starting_capital
    savings = annual_savings
    spend = annual_spend
    income = annual_income

    current_ss_annual = ss_monthly_benefit * 12
    current_wage_base = SS_WAGE_BASE
    current_year = datetime.datetime.now().year

    for i in range(years_to_sim):
        withdrawal_tax = 0
        gross_withdrawal = 0
        inv_returns = 0
        display_income = 0
        display_income_tax = 0
        display_fica = 0

        if age < retire_age:
            fica_tax = min(income, current_wage_base) * SS_TAX_RATE
            inv_returns = wealth * net_pre
            tax_bill = income * tax_rate_inc

            display_income = income
            display_income_tax = tax_bill
            display_fica = fica_tax

            surplus = income - tax_bill - fica_tax - spend
            leakage = surplus - savings
        else:
            fica_tax = 0
            leakage = 0
            inv_returns = wealth * net_post

            spending_gap = spend - current_ss_annual
            if spending_gap > 0:
                gross_withdrawal = spending_gap / (1 - tax_rate_inv)
                withdrawal_tax = gross_withdrawal - spending_gap

        data.append({
            "Year": current_year + i,
            "Age": age,
            "Invested Assets": round(wealth),
            "Income": round(display_income),
            "Income Tax": round(display_income_tax),
            "FICA Tax": round(display_fica),
            "Social Security": round(current_ss_annual) if age >= retire_age else 0,
            "Investment Returns": round(inv_returns),
            "Expenses": round(spend),
            "Savings Contribution": round(savings) if age < retire_age else 0,
            "Gross Withdrawal": round(gross_withdrawal),
            "Withdrawal Tax": round(withdrawal_tax),
            "Savings Capacity Gap": round(leakage)
        })

        if age < retire_age:
            wealth = wealth * (1 + net_pre) + savings
            savings *= (1 + (savings_growth_rate / 100))
            spend *= (1 + inflation)
            income *= (1 + inflation)
            current_ss_annual *= (1 + inflation)
            current_wage_base *= (1 + inflation)
        else:
            wealth = wealth * (1 + net_post) - gross_withdrawal
            spend *= (1 + inflation)
            current_ss_annual *= (1 + inflation)
            income = 0
            savings = 0

        if wealth < 0: wealth = 0
        age += 1

    return pd.DataFrame(data)

def make_interactive_chart(df, color_hex, path_data=None):
    """
    Creates chart. If path_data is provided, creates shaded bands.
    """

    # Base Line Chart (Median/Deterministic Path)
    line = alt.Chart(df).mark_line(color=color_hex, strokeWidth=3).encode(
        x=alt.X('Age', axis=alt.Axis(title='Client Age')),
        y=alt.Y('Invested Assets', axis=alt.Axis(format='$,.0f')),
        tooltip=[
            alt.Tooltip('Year'), alt.Tooltip('Age'), alt.Tooltip('Invested Assets', format='$,.0f'),
            alt.Tooltip('Investment Returns', format='$,.0f'), alt.Tooltip('Income', format='$,.0f'),
            alt.Tooltip('Income Tax', format='$,.0f'), alt.Tooltip('FICA Tax', format='$,.0f'),
            alt.Tooltip('Social Security', format='$,.0f'), alt.Tooltip('Expenses', format='$,.0f'),
            alt.Tooltip('Savings Contribution', format='$,.0f'), alt.Tooltip('Gross Withdrawal', format='$,.0f'),
            alt.Tooltip('Withdrawal Tax', format='$,.0f'), alt.Tooltip('Savings Capacity Gap', format='$,.0f')
        ]
    )

    if path_data and 'p25' in path_data:
        # Create a separate DF for the bands
        df_band = df[['Age']].copy()
        df_band['P05'] = path_data['p05']
        df_band['P25'] = path_data['p25']
        df_band['P75'] = path_data['p75']
        df_band['P95'] = path_data['p95']

        # Create formatted range strings for tooltips
        df_band['Middle Range'] = df_band.apply(lambda x: f"${x['P25']:,.0f} - ${x['P75']:,.0f}", axis=1)
        df_band['Worst Range'] = df_band.apply(lambda x: f"${x['P05']:,.0f} - ${x['P25']:,.0f}", axis=1)
        df_band['Best Range'] = df_band.apply(lambda x: f"${x['P75']:,.0f} - ${x['P95']:,.0f}", axis=1)

        # Band 1: Middle 50% (Likely) - Darkest Opacity
        band_middle = alt.Chart(df_band).mark_area(opacity=0.3, color=color_hex).encode(
            x='Age', y='P25', y2='P75',
            tooltip=[alt.Tooltip('Middle Range', title='Middle 50% (Likely)')]
        )

        # Band 2: Worst 25% (5th-25th) - Lighter Opacity
        band_worst = alt.Chart(df_band).mark_area(opacity=0.15, color='#D93025').encode( # Red tint for risk
            x='Age', y='P05', y2='P25',
            tooltip=[alt.Tooltip('Worst Range', title='Bottom 25% (Unfavorable)')]
        )

        # Band 3: Best 25% (75th-95th) - Lighter Opacity
        band_best = alt.Chart(df_band).mark_area(opacity=0.15, color='#00B140').encode( # Green tint for upside
            x='Age', y='P75', y2='P95',
            tooltip=[alt.Tooltip('Best Range', title='Top 25% (Favorable)')]
        )

        # Combine: Bands in background, Line on top
        return (band_worst + band_best + band_middle + line).interactive()

    return line.interactive()

# --- SOLVERS ---

def solve_for_savings(target_prob, locked_inputs, sim_duration, ss_benefit, params):
    test_savings = locked_inputs['savings']
    for _ in range(300):
        p, r, _ = run_monte_carlo(
            locked_inputs['capital'], test_savings, locked_inputs['expenses'],
            locked_inputs['age'], locked_inputs['retire_age'], locked_inputs['growth'],
            sim_duration, ss_benefit, params
        )
        if p >= target_prob:
            return test_savings
        test_savings += 1000
    return test_savings

def solve_for_age(target_prob, locked_inputs, sim_duration, ss_benefit, params):
    test_ret_age = locked_inputs['retire_age']
    end_age = locked_inputs['end_age']
    while test_ret_age < end_age:
        p, r, _ = run_monte_carlo(
            locked_inputs['capital'], locked_inputs['savings'], locked_inputs['expenses'],
            locked_inputs['age'], test_ret_age, locked_inputs['growth'],
            sim_duration, ss_benefit, params
        )
        if p >= target_prob:
            return test_ret_age
        test_ret_age += 1
    return end_age

def solve_for_earlier_age(target_prob, locked_inputs, sim_duration, ss_benefit, params):
    test_ret_age = locked_inputs['retire_age']
    min_age = locked_inputs['age'] + 1
    while test_ret_age > min_age:
        p, r, _ = run_monte_carlo(
            locked_inputs['capital'], locked_inputs['savings'], locked_inputs['expenses'],
            locked_inputs['age'], test_ret_age - 1, locked_inputs['growth'],
            sim_duration, ss_benefit, params
        )
        if p < target_prob:
            return test_ret_age
        test_ret_age -= 1
    return test_ret_age

def solve_for_expenses(target_prob, locked_inputs, sim_duration, ss_benefit, params):
    test_spend = locked_inputs['expenses']
    p_initial, _, _ = run_monte_carlo(
        locked_inputs['capital'], locked_inputs['savings'], test_spend,
        locked_inputs['age'], locked_inputs['retire_age'], locked_inputs['growth'],
        sim_duration, ss_benefit, params
    )
    if p_initial >= target_prob:
        step = 1000
        for _ in range(200):
            p, _, _ = run_monte_carlo(
                locked_inputs['capital'], locked_inputs['savings'], test_spend + step,
                locked_inputs['age'], locked_inputs['retire_age'], locked_inputs['growth'],
                sim_duration, ss_benefit, params
            )
            if p < target_prob:
                return test_spend
            test_spend += step
    else:
        step = 1000
        for _ in range(200):
            if test_spend <= 20000: break
            p, _, _ = run_monte_carlo(
                locked_inputs['capital'], locked_inputs['savings'], test_spend - step,
                locked_inputs['age'], locked_inputs['retire_age'], locked_inputs['growth'],
                sim_duration, ss_benefit, params
            )
            if p >= target_prob:
                return test_spend - step
            test_spend -= step
    return test_spend

# ======================================================
# PAGE 1: INPUT SCREEN
# ======================================================
if st.session_state.page == 'input':

    col_logo, col_title = st.columns([1, 4])
    with col_title:
        st.markdown("""
        <div style="margin-bottom: 20px;">
            <div class="brand-text">nerdwallet <span class="brand-accent">Wealth Partners</span></div>
            <div class="sub-brand">Estimate Your Retirement</div>
        </div>
        """, unsafe_allow_html=True)

    if st.session_state.show_warning:
        st.warning("⚠️ Alert: Inputted savings greater than calculated savings capacity.")
        st.write("Your inputs indicate you are saving more than your theoretical surplus (Income - Taxes - Expenses).")
        st.write("Are you ok to proceed with this data?")
        col_w1, col_w2 = st.columns(2)
        if col_w1.button("Go Back to Edit Inputs"):
            go_back_to_edit()
            st.rerun()
        if col_w2.button("Proceed with Calculation"):
            proceed_despite_warning()
            st.rerun()
    else:
        st.markdown("""
        Input your details below to generate a free probability assessment

        Want to speak to a profesional? Book a free call with a
        <a href="https://www.nerdwallet.com/l/wealth/advisors" target="_blank">NerdWallet Wealth Partner</a> to discuss your results
        """, unsafe_allow_html=True)

        with st.form("client_input_form"):
            c1, c2 = st.columns(2)
            with c1:
                st.subheader("Profile")
                st.number_input("Current Age", min_value=18, max_value=90, value=st.session_state['in_age'], key="in_age")
                st.number_input("Target Retirement Age", min_value=50, max_value=70, value=st.session_state['in_retire_age'], key="in_retire_age")
                st.number_input("End of Plan Age (Life Expectancy)", min_value=50, max_value=100, value=st.session_state['in_end_age'], key="in_end_age")
            with c2:
                st.subheader("Income & Spending")
                st.number_input("Current Annual Income ($)", step=1000, value=st.session_state['in_income'], key="in_income")
                st.number_input("Annual Living Expenses ($)", step=1000, value=st.session_state['in_expenses'], key="in_expenses")

            st.markdown("---")
            st.markdown("### Savings and Investments")
            sc1, sc2 = st.columns(2)
            with sc1:
                st.number_input("Total Invested Assets ($)", step=1000, value=st.session_state['in_capital'], key="in_capital")
                st.number_input("Actual Annual Savings Amount ($)", step=1000, value=st.session_state['in_savings'], key="in_savings", help="Any surplus not listed here is considered 'Leakage'.")
            with sc2:
                st.number_input("Annual Savings Growth Rate (%)", step=0.5, value=st.session_state['in_growth'], key="in_growth", help="How much will your contributions increase each year?")

            st.markdown("<br>", unsafe_allow_html=True)
            submitted = st.form_submit_button("CALCULATE PROJECTION", on_click=check_inputs)

        if st.button("Reset Input Fields to Default"):
            restore_client_defaults()

# ======================================================
# PAGE 2: OUTPUT DASHBOARD
# ======================================================
elif st.session_state.page == 'output':

    scen = st.session_state.locked_scenario
    calc_ss_benefit = calculate_primary_insurance_amount(scen['income'])
    c_ss_benefit = st.session_state.get('ss_override', calc_ss_benefit)
    SIM_DURATION = int(scen['end_age'] - scen['age'])
    if SIM_DURATION <= 0: SIM_DURATION = 1
    params = st.session_state.company_params

    with st.sidebar:
        st.markdown('<div class="brand-text" style="font-size:18px;">nerdwallet <span class="brand-accent">Wealth Partners</span></div>', unsafe_allow_html=True)
        st.markdown("---")
        st.header("Data Reference")
        st.subheader("Client Inputs")
        st.table(pd.DataFrame({
            "Input": ["Age", "Retire Age", "End Age", "Income", "Expenses", "Assets", "Savings"],
            "Value": [scen['age'], scen['retire_age'], scen['end_age'], f"${scen['income']/1000:.0f}k", f"${scen['expenses']/1000:.0f}k", f"${scen['capital']/1000:.0f}k", f"${scen['savings']/1000:.0f}k"]
        }))
        st.button("⬅ Edit Inputs", on_click=go_to_input)
        st.markdown("---")
        st.subheader("Company Assumptions")
        admin_pass = st.text_input("Admin Password", type="password")

        if admin_pass == "nwwp":
            st.success("Admin Mode Unlocked")
            with st.form("admin_panel"):
                new_ss = st.number_input("Mo. SS Benefit (Calculated)", value=c_ss_benefit, step=100)
                new_inc_tax = st.number_input("Income Tax Rate", value=params['tax_rate_inc'], format="%.2f")
                new_inv_tax = st.number_input("Cap Gains Tax Rate", value=params['tax_rate_inv'], format="%.2f")
                new_infl = st.number_input("Inflation Rate", value=params['inflation'], format="%.2f")
                new_pre = st.number_input("Pre-Ret Return", value=params['pre_ret_return'], format="%.2f")
                new_post = st.number_input("Post-Ret Return", value=params['post_ret_return'], format="%.2f")
                new_fee = st.number_input("Advisor Fee", value=params['advisor_fee'], format="%.3f")

                if st.form_submit_button("Save & Rerun"):
                    st.session_state.ss_override = new_ss
                    st.session_state.company_params = {
                        "tax_rate_inc": new_inc_tax, "tax_rate_inv": new_inv_tax, "inflation": new_infl,
                        "pre_ret_return": new_pre, "post_ret_return": new_post, "advisor_fee": new_fee
                    }
                    st.rerun()
            if st.button("Restore Admin Defaults"):
                restore_admin_defaults()
        else:
            curr = params
            comp_data = {
                "Metric": ["Mo. SS Benefit", "Inc Tax", "CG Tax", "Inflation", "Pre-Ret %", "Post-Ret %", "Fee"],
                "Val": [f"${c_ss_benefit:,.0f}", f"{curr['tax_rate_inc']*100:.0f}%", f"{curr['tax_rate_inv']*100:.0f}%", f"{curr['inflation']*100:.0f}%", f"{curr['pre_ret_return']*100:.0f}%", f"{curr['post_ret_return']*100:.0f}%", f"{curr['advisor_fee']*100:.1f}%"]
            }
            st.table(pd.DataFrame(comp_data))

    st.title("Retirement Estimate")

    # BASELINE CALC
    base_prob, base_ruin, base_paths = run_monte_carlo(
        scen['capital'], scen['savings'], scen['expenses'], scen['age'],
        scen['retire_age'], scen['growth'], SIM_DURATION, c_ss_benefit, params, return_paths=True
    )
    df_baseline = generate_detailed_ledger(
        scen['capital'], scen['income'], scen['savings'], scen['expenses'], scen['age'],
        scen['retire_age'], scen['growth'], SIM_DURATION, c_ss_benefit, params
    )

    st.subheader("Baseline Results")

    # Only display Probability of Success as requested
    color = "inverse" if base_prob < 50 else "normal"
    label = "CRITICAL RISK" if base_prob < 50 else "ON TRACK"
    st.metric("Probability of Success", f"{base_prob:.1f}%", label, delta_color=color)

    if base_prob < 50:
        st.error(f"INSOLVENCY ALERT: Funds depleted by Age {int(base_ruin)}. Scroll below to use our retirement optimizer to understand how you can achieve your retirement goals.")
    else:
        st.success(f"EXCELLENT: You are currently on track to fund your retirement until Age {int(base_ruin)}.")

    if not st.session_state.show_optimizer:
        if base_prob < 50:
            st.markdown("#### Analysis")
            st.write("Would you like to achieve higher confidence in your ability to retire? Use our optimizer here to understand what options you have to achieve your retirement dreams.")
            st.button("Optimize my retirement", on_click=enable_optimizer)
        else:
            st.markdown("#### Analysis")
            st.write("You are well positioned! Use our optimizer to see if you can retire earlier or what other goals you can acheive. Meet with a NerdWallet Wealth Partner to learn more")
            st.button("Unlock Optimization Tools", on_click=enable_optimizer)

    st.markdown("Move your mouse over the line to see details for that specific year.")
    st.altair_chart(make_interactive_chart(df_baseline, "#00B140", base_paths), use_container_width=True)

    # OPTIMIZER
    if st.session_state.show_optimizer:
        st.markdown("---")
        st.subheader("Optimized Results")

        st.info("A minimum 50% probability is used to gauge likely retirement. If a higher probability is desired, use the slider below.")

        col_opt_1, col_opt_2 = st.columns([1, 3])
        with col_opt_1:
            st.markdown("#### Goal Setting")
            if base_prob < 50:
                opt_min, opt_max, opt_val = 50, 100, 50
            else:
                opt_min, opt_max, opt_val = 50, int(base_prob), 50
                if opt_max < 50: opt_max = 50
            target_conf = st.slider("Desired Probability of Success", min_value=opt_min, max_value=opt_max, value=opt_val, step=1)

        with st.spinner(f"Solving for {target_conf}% Probability..."):
            if base_prob < 50:
                tab_a_label, tab_b_label = "Strategy A: Save More", "Strategy B: Retire Later"
                res_a = solve_for_savings(target_conf, scen, SIM_DURATION, c_ss_benefit, params)
                res_b = solve_for_age(target_conf, scen, SIM_DURATION, c_ss_benefit, params)

                _, _, paths_a = run_monte_carlo(scen['capital'], res_a, scen['expenses'], scen['age'], scen['retire_age'], scen['growth'], SIM_DURATION, c_ss_benefit, params, return_paths=True)
                _, _, paths_b = run_monte_carlo(scen['capital'], scen['savings'], scen['expenses'], scen['age'], res_b, scen['growth'], SIM_DURATION, c_ss_benefit, params, return_paths=True)

                df_a = generate_detailed_ledger(scen['capital'], scen['income'], res_a, scen['expenses'], scen['age'], scen['retire_age'], scen['growth'], SIM_DURATION, c_ss_benefit, params)
                df_b = generate_detailed_ledger(scen['capital'], scen['income'], scen['savings'], scen['expenses'], scen['age'], res_b, scen['growth'], SIM_DURATION, c_ss_benefit, params)

                val_a_display = f"${res_a:,.0f}"
                delta_a_display = f"+${res_a - scen['savings']:,.0f} / year"

                new_savings_rate = (res_a / scen['income']) * 100
                if new_savings_rate <= 20:
                    rate_note = f"This represents {new_savings_rate:.1f}% of your income, which is within the recommended 20% benchmark."
                else:
                    rate_note = f"High Saver Alert: This represents {new_savings_rate:.1f}% of your income, exceeding the typical 20% benchmark."

                val_b_display = f"{res_b}"
                delta_b_display = f"+{res_b - scen['retire_age']} Years"
                desc_a = "Requires increasing your savings rate. Speak with a NerdWallet Wealth Advisor to help acheive your goals"
                desc_b = "Requires delaying retirement to accumulate more. Speak with a NerdWallet Wealth Advisor to help acheive your goals"
            else:
                tab_a_label, tab_b_label = "Strategy A: Retire Earlier", "Strategy B: Adjust Spending"
                res_a = solve_for_earlier_age(target_conf, scen, SIM_DURATION, c_ss_benefit, params)
                res_b = solve_for_expenses(target_conf, scen, SIM_DURATION, c_ss_benefit, params)

                _, _, paths_a = run_monte_carlo(scen['capital'], scen['savings'], scen['expenses'], scen['age'], res_a, scen['growth'], SIM_DURATION, c_ss_benefit, params, return_paths=True)
                _, _, paths_b = run_monte_carlo(scen['capital'], scen['savings'], res_b, scen['age'], scen['retire_age'], scen['growth'], SIM_DURATION, c_ss_benefit, params, return_paths=True)

                df_a = generate_detailed_ledger(scen['capital'], scen['income'], scen['savings'], scen['expenses'], scen['age'], res_a, scen['growth'], SIM_DURATION, c_ss_benefit, params)
                df_b = generate_detailed_ledger(scen['capital'], scen['income'], scen['savings'], res_b, scen['age'], scen['retire_age'], scen['growth'], SIM_DURATION, c_ss_benefit, params)

                val_a_display = f"{res_a}"
                delta_a_display = f"-{scen['retire_age'] - res_a} Years"
                val_b_display = f"${res_b:,.0f}"
                delta = res_b - scen['expenses']
                delta_b_display = f"+${delta:,.0f}" if delta >= 0 else f"-${abs(delta):,.0f}"
                desc_a = "You have enough capital to stop working sooner."
                desc_b = "Amount you can safely spend annually."

        tab1, tab2 = st.tabs([tab_a_label, tab_b_label])
        with tab1:
            st.markdown(f"#### {tab_a_label}")
            c1, c2 = st.columns(2)
            c1.metric(val_a_label if 'val_a_label' in locals() else "Target", val_a_display, delta_a_display)
            c2.info(desc_a)
            if 'rate_note' in locals():
                st.caption(rate_note)
            st.altair_chart(make_interactive_chart(df_a, "#FFD700", paths_a).properties(title="Optimized Path"), use_container_width=True)
        with tab2:
            st.markdown(f"#### {tab_b_label}")
            c1, c2 = st.columns(2)
            c1.metric(val_b_label if 'val_b_label' in locals() else "Target", val_b_display, delta_b_display)
            c2.info(desc_b)
            st.altair_chart(make_interactive_chart(df_b, "#008F4F", paths_b).properties(title="Optimized Path"), use_container_width=True)

    st.markdown("---")
    st.subheader("Export Report")
    col_dl_1, col_dl_2 = st.columns([1, 2])
    with col_dl_1:
        dl_pass_input = st.text_input("Enter Password to Download", type="password", key="dl_pass")
        if dl_pass_input == "nwwp":
            csv_data = df_baseline.to_csv(index=False).encode('utf-8')
            st.download_button(label="Download Baseline Spreadsheet", data=csv_data, file_name="retirement_ledger.csv", mime="text/csv")
        elif dl_pass_input:
            st.error("Incorrect password.")
